# pytest.ini
[pytest]
python_functions = test_*
markers =
    llm_ollama_models: a marker to run llm_ollama_models
    llm_open_ai_models: a marker to run llm_open_ai_models
    llm_platform_provider_open_ai: a marker to run llm_platform_provider_open_ai
